# Generated by Django 3.2.9 on 2022-11-28 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profession', models.TextField(max_length=2000)),
                ('about', models.TextField(max_length=2000)),
                ('birthday', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('describe', models.TextField(max_length=2000)),
                ('facts', models.TextField(max_length=200)),
                ('clients', models.CharField(max_length=2000)),
                ('projects', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('experience_years', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=20000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_details_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField(max_length=2000)),
                ('discription', models.TextField(max_length=2000)),
                ('role', models.TextField(max_length=2000)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='user_details_testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000)),
                ('role', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=2000)),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='user_details_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.TextField(max_length=2000)),
                ('linkedin', models.TextField(max_length=2000)),
                ('instagram', models.TextField(max_length=2000)),
                ('gmail', models.TextField(max_length=2000)),
                ('facebook', models.TextField(max_length=2000)),
                ('skype', models.TextField(max_length=2000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='user_details_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_college', models.TextField(max_length=2000)),
                ('education_years', models.TextField(max_length=2000)),
                ('education_degree', models.TextField(max_length=2000)),
                ('education_speacialization', models.TextField(max_length=2000)),
                ('education_cgpa', models.TextField(max_length=2000)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user_details')),
            ],
        ),
    ]
