# Generated by Django 3.2.9 on 2022-11-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_user_details_user_details_education_user_details_social_user_details_testimonial_user_details_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_check',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
