# Generated by Django 3.2.9 on 2022-12-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_details_check_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='describe',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='about',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='facts',
            field=models.TextField(default='noname', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profession',
            field=models.TextField(default='Hard Worker', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='skills',
            field=models.TextField(default='noname', max_length=20000),
        ),
        migrations.AlterField(
            model_name='user_details_social',
            name='facebook',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details_social',
            name='gmail',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details_social',
            name='instagram',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details_social',
            name='linkedin',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details_social',
            name='skype',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_details_social',
            name='twitter',
            field=models.TextField(default='noname', max_length=2000),
        ),
    ]
