# Generated by Django 3.2.9 on 2022-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20221205_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='equity',
            field=models.CharField(default='noname', max_length=20000),
        ),
        migrations.AddField(
            model_name='user_details',
            name='freelance',
            field=models.CharField(default='NO', max_length=20000),
        ),
    ]
