# Generated by Django 3.2.9 on 2022-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_user_details_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details_work',
            name='employer',
            field=models.TextField(default='NA', max_length=2000),
        ),
    ]
