# Generated by Django 3.2.9 on 2022-12-05 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0008_user_details_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='noname', max_length=2000)),
                ('about', models.TextField(default='noname', max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='income_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.CharField(default='1', max_length=200)),
                ('year', models.CharField(default='2022', max_length=200)),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.company_details')),
            ],
        ),
        migrations.CreateModel(
            name='company_job_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.company_details')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='company_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='2022', max_length=200)),
                ('experience', models.CharField(default='0', max_length=200)),
                ('description', models.TextField(default='noname', max_length=2000)),
                ('salary', models.CharField(default='2022', max_length=200)),
                ('skills', models.CharField(default='C++', max_length=200)),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.company_details')),
            ],
        ),
        migrations.CreateModel(
            name='company_hired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.company_details')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user_details')),
            ],
        ),
    ]
