# Generated by Django 3.2.9 on 2022-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_company_details_company_hired_company_job_company_job_applications_income_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_company',
            name='value',
            field=models.CharField(default='2022', max_length=200),
        ),
    ]
