# Generated by Django 3.2.9 on 2022-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_company_details_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='address',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AddField(
            model_name='company_details',
            name='funding',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AddField(
            model_name='company_details',
            name='size',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AddField(
            model_name='company_details',
            name='website',
            field=models.TextField(default='noname', max_length=2000),
        ),
    ]
