# Generated by Django 3.2.9 on 2022-12-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20221205_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_job_applications',
            name='comapny',
        ),
        migrations.AddField(
            model_name='company_job_applications',
            name='hire_id',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AddField(
            model_name='company_job_applications',
            name='job',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='basic.company_job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_job_applications',
            name='name',
            field=models.TextField(default='noname', max_length=2000),
        ),
    ]
