# Generated by Django 3.2.9 on 2022-12-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_auto_20221205_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='skills',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
