# Generated by Django 3.2.9 on 2022-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_alter_user_details_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='ratings',
            field=models.CharField(default='4', max_length=20000),
        ),
    ]
