# Generated by Django 3.2.9 on 2022-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_auto_20221207_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='equity',
            field=models.CharField(default='0', max_length=20000),
        ),
    ]
