# Generated by Django 3.2.9 on 2022-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_company_or_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_job',
            name='catagory',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AddField(
            model_name='company_job',
            name='country',
            field=models.TextField(default='noname', max_length=2000),
        ),
        migrations.AddField(
            model_name='company_job',
            name='location',
            field=models.TextField(default='noname', max_length=2000),
        ),
    ]
