# Generated by Django 3.2.9 on 2022-12-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_company_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_job',
            name='equity',
            field=models.TextField(default='NO', max_length=2000),
        ),
    ]
