# Generated by Django 3.2.9 on 2022-12-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_company_job_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='email',
            field=models.TextField(default='noname', max_length=2000),
        ),
    ]
